### ISSUE TITLE
chrome.storage.sync instead of chrome.storage.local

### ISSUE THREAD

**Issue by csbenjamin** [Rob--W/pdf.js#5]
Is there any chance to use chrome.storage.sync to store the history? Thus the database will be stored on the cloud and it will be synced over all computer that the user is logged in into chrome with a google account. Doing that, if I have some online pdf document, something like www.example.com/myOnlinePdf.pdf, I can open in my office computer, start reading it and later, when I get home, I can open that pdf url and I can continue reading where I had stopped when I was in the office. What do you think?

**Comment by Rob--W** [comment]
Sounds good to me. Please put this ticket on the main issue tracker at the mozilla/pdf.js repo.
