### ISSUE TITLE
Disable option

### ISSUE THREAD

**Issue by choltz95** [Rob--W/pdf.js#6]
Can we add an option to disable/enable on click? Chrome's default pdf viewer loads pdfs much faster then pdf.js, but pdf.js supports opening pdfs in presentation mode.

**Comment by Rob--W** [comment]
Go to `chrome://extensions`and disable the extension.
Then, when you do want to use it, visit `chrome://extensions` again, but then to re-enable it.

You can access `chrome://extensions` in many ways, either by directly typing the URL in the omnibox, by clicking on "Extensions" in the menu or by right-clicking on an extension button in the toolbar and choosing "Manage extensions".
