### ISSUE TITLE
Viewing PDF in Light Theme

### ISSUE THREAD

**Issue by Li-Xiang-Ideal** [Rob--W/pdf.js#8]
Last year pdf.js released the light theme but I can't use it in this extension yet. It seems that the light theme update hasn't been added to the extension. Could you update it to the light theme version? Cheers.

**Comment by Rob--W** [comment]
I'm preparing an update, the progress is at: https://github.com/mozilla/pdf.js/issues/13669
The updated viewer will be dark by default, with an option to choose the light theme in the options page.

Not PDF.js-specific is that I'm trying to get the Chrome Web Store to accept my submissions, details about that are at https://github.com/Rob--W/stackexchange-notifications/issues/31

**Comment by Rob--W** [comment]
FYI the published version supports Light theme at the settings page.
